name: CI/CD Pipeline

# when does this workflow run
on:
    push:
        branches: [main] # Run on push to main
    pull_request:
        branches: [main] # Run on PRs to main

jobs:
    # Job1 : Build and Test
    build:
        runs-on: ubuntu-latest
        steps:
            # Step1: Get the code
            - name: Checkout code
              uses: actions/checkout@v4

            # Step2: Build Docker image
            - name: Build Docker image
              run: docker build -t my-static-site:${{ github.sha }} .

            # Step3: Test - Run container and check if it responds
            - name: Test container
              run: |
                  docker run -d -p 8080:80 --name test-container my-static-site:${{ github.sha }}
                  sleep 5
                  curl --fail http://localhost:8080 || exit 1
                  docker stop test-container

            # Step4: show success message
            - name: Build successful
              run: echo "Build and test passed!"

    # Job2: Deploy (Only runs on main branch, after build succeeds)
    deploy:
        needs: build # Wait for build job
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' # Only on main branch
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push to Docker hub
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ secrets.DOCKER_USERNAME }}/my-static-site:latest
                      ${{ secrets.DOCKER_USERNAME }}/my-static-site:${{ github.sha }}

            - name: Deploy successful
              run: echo "Deployed to Docker Hub"
